apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-app-demo
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
  annotations:
    sonarqube.org/project-key: backstage
    backstage.io/kubernetes-id: backstage
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
